spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inc?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root@123!
app:
  #服务器配置
  #filePath: /Users/zhangdi/home/proj/inc/uploaded_files/
  filePath: D:/project/practical/files/uploaded_files/
  #计数文件路径
  countFilePath: D:/project/practical/files/pre_files/incfile/
  pre: D:/project/practical/files/pre_files/